export const techLinks: Record<string, string> = {
    "Next.js": "https://nextjs.org/docs",
    "React": "https://react.dev",
    "TypeScript": "https://www.typescriptlang.org/docs/",
    "Node.js": "https://nodejs.org/en/docs",
    "HTML5": "https://developer.mozilla.org/en-US/docs/Web/HTML",
    "CSS3": "https://developer.mozilla.org/en-US/docs/Web/CSS",
    "Tailwind": "https://tailwindcss.com/docs",
    "Tailwind (Expert)": "https://tailwindcss.com/docs",
    "Vanilla CSS": "https://developer.mozilla.org/en-US/docs/Web/CSS",
    "Git": "https://git-scm.com/doc",
    "REST APIs": "https://restfulapi.net/",
    "Django": "https://docs.djangoproject.com/",
    "AWS": "https://aws.amazon.com/what-is-aws/",
    "Figma": "https://help.figma.com/",
    "Google Maps API": "https://developers.google.com/maps",
    "Google Maps": "https://developers.google.com/maps",
    "Redux": "https://redux.js.org/",
    "GraphQL": "https://graphql.org/",
    "SSR": "https://nextjs.org/docs/pages/building-your-application/rendering/server-side-rendering",
    "Bootstrap": "https://getbootstrap.com/docs/5.3/getting-started/introduction/",
    "JavaScript": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    "HTML/CSS": "https://developer.mozilla.org/en-US/docs/Web/HTML",
    "C++": "https://en.cppreference.com/w/",
    "AWS EC2": "https://aws.amazon.com/ec2/"
};
